// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnMdxGNriuw4GkjeOEQt5JtRBpgY_1Uow',
    appId: '1:355848702282:web:c75226359a2520046659b3',
    messagingSenderId: '355848702282',
    projectId: 'gazitubitak-74048',
    authDomain: 'gazitubitak-74048.firebaseapp.com',
    storageBucket: 'gazitubitak-74048.appspot.com',
    measurementId: 'G-Z7MZ9QDXPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBffzcXI7bwSmzBzdlJJx9keFntNsCKp2s',
    appId: '1:355848702282:android:1fa7799649d43dfb6659b3',
    messagingSenderId: '355848702282',
    projectId: 'gazitubitak-74048',
    storageBucket: 'gazitubitak-74048.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNtutddROg6Ll7NFauQ_vKOHiGuHSUEjM',
    appId: '1:355848702282:ios:e43baf50559931016659b3',
    messagingSenderId: '355848702282',
    projectId: 'gazitubitak-74048',
    storageBucket: 'gazitubitak-74048.appspot.com',
    iosClientId: '355848702282-bsg92e1dbg3ni3mrrlksinpvi9u22ado.apps.googleusercontent.com',
    iosBundleId: 'com.example.gazihealty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNtutddROg6Ll7NFauQ_vKOHiGuHSUEjM',
    appId: '1:355848702282:ios:e43baf50559931016659b3',
    messagingSenderId: '355848702282',
    projectId: 'gazitubitak-74048',
    storageBucket: 'gazitubitak-74048.appspot.com',
    iosClientId: '355848702282-bsg92e1dbg3ni3mrrlksinpvi9u22ado.apps.googleusercontent.com',
    iosBundleId: 'com.example.gazihealty',
  );
}
